export enum DisputeType {
  SPOT_TAKEN_BY_STRANGER = 'SPOT_TAKEN_BY_STRANGER',
  LEAVER_DID_NOT_LEAVE = 'LEAVER_DID_NOT_LEAVE',
  WRONG_LOCATION = 'WRONG_LOCATION',
  SEARCHER_NO_SHOW = 'SEARCHER_NO_SHOW',
}

export enum DisputeStatus {
  PENDING = 'PENDING',
  AUTO_RESOLVED = 'AUTO_RESOLVED',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
  REJECTED = 'REJECTED',
}
